server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: passw0rd
    driver-class-name: org.postgresql.Driver

#  cache on redis
  cache:
    type: redis
    redis:
      cache-null-values:  false
      time-to-live: 600000
      use-key-prefix: true    
       
  redis:
    host: localhost
    port: 6379
    password: passw0rd
        
# Kafka
  kafka:
    bootstrap-servers: localhost:9092
    listener.ack-mode: manual_immediate    
# Kafka Producer
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# Kafka Consumer
    consumer:
      group-id: stock-group
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
mybatis:
  config-location: classpath:mybatis-config.xml
academy:
  stock-qty: 100000
  stock-max-count: 1000 
kafka:
  stock:
    topic: stock-order   
